import { useState, useCallback } from 'react';
import type { ThemeMode, Track } from '../types';
import { getTrackGpxString, exportTrackGpx } from '../hooks/useTauri';

interface ShareTrackModalProps {
  theme: ThemeMode;
  track: Track;
  onClose: () => void;
}

type ShareStatus = 'idle' | 'loading' | 'success' | 'error';

export function ShareTrackModal({ theme, track, onClose }: ShareTrackModalProps) {
  const [status, setStatus] = useState<ShareStatus>('idle');
  const [statusMessage, setStatusMessage] = useState<string>('');

  const showStatus = useCallback((message: string, isSuccess: boolean) => {
    setStatus(isSuccess ? 'success' : 'error');
    setStatusMessage(message);
    setTimeout(() => {
      setStatus('idle');
      setStatusMessage('');
    }, 3000);
  }, []);

  // Format track info for summary
  const formatTrackSummary = useCallback(() => {
    const lines = [`Track: ${track.name}`];

    if (track.description) {
      lines.push(`Description: ${track.description}`);
    }

    if (track.total_distance_nm) {
      lines.push(`Distance: ${track.total_distance_nm.toFixed(2)} nm`);
    }

    lines.push(`Points: ${track.point_count}`);

    if (track.started_at) {
      lines.push(`Started: ${new Date(track.started_at).toLocaleString()}`);
    }

    if (track.ended_at) {
      lines.push(`Ended: ${new Date(track.ended_at).toLocaleString()}`);
    }

    if (track.started_at && track.ended_at) {
      const start = new Date(track.started_at);
      const end = new Date(track.ended_at);
      const durationMs = end.getTime() - start.getTime();
      const hours = Math.floor(durationMs / (1000 * 60 * 60));
      const minutes = Math.floor((durationMs % (1000 * 60 * 60)) / (1000 * 60));
      lines.push(`Duration: ${hours > 0 ? `${hours}h ` : ''}${minutes}m`);
    }

    lines.push('');
    lines.push('Generated by VortexNav');

    return lines.join('\n');
  }, [track]);

  // Copy track summary text to clipboard
  const handleCopySummary = useCallback(async () => {
    setStatus('loading');
    try {
      const summary = formatTrackSummary();
      await navigator.clipboard.writeText(summary);
      showStatus('Track summary copied to clipboard!', true);
    } catch (error) {
      console.error('Failed to copy summary:', error);
      showStatus('Failed to copy summary', false);
    }
  }, [formatTrackSummary, showStatus]);

  // Copy GPX XML to clipboard
  const handleCopyGpx = useCallback(async () => {
    if (!track.id) return;

    setStatus('loading');
    try {
      const gpx = await getTrackGpxString(track.id);
      await navigator.clipboard.writeText(gpx);
      showStatus('GPX copied to clipboard!', true);
    } catch (error) {
      console.error('Failed to copy GPX:', error);
      showStatus('Failed to copy GPX', false);
    }
  }, [track.id, showStatus]);

  // Download GPX file
  const handleDownloadGpx = useCallback(async () => {
    if (!track.id) return;

    setStatus('loading');
    try {
      // Use Tauri's save dialog
      const { save } = await import('@tauri-apps/plugin-dialog');
      const filePath = await save({
        defaultPath: `${track.name.replace(/[^a-zA-Z0-9]/g, '_')}.gpx`,
        filters: [{ name: 'GPX Files', extensions: ['gpx'] }],
      });

      if (filePath) {
        await exportTrackGpx(track.id, filePath);
        showStatus('GPX file saved!', true);
      } else {
        setStatus('idle');
      }
    } catch (error) {
      console.error('Failed to download GPX:', error);
      showStatus('Failed to save GPX file', false);
    }
  }, [track.id, track.name, showStatus]);

  // Use system share if available
  const handleSystemShare = useCallback(async () => {
    try {
      const summary = formatTrackSummary();

      if (navigator.share) {
        await navigator.share({
          title: track.name,
          text: summary,
        });
        showStatus('Shared successfully!', true);
      } else {
        // Fallback: copy to clipboard
        await navigator.clipboard.writeText(summary);
        showStatus('Share not available - copied to clipboard', true);
      }
    } catch (error) {
      if ((error as Error).name !== 'AbortError') {
        console.error('Failed to share:', error);
        showStatus('Failed to share', false);
      }
    }
  }, [track.name, formatTrackSummary, showStatus]);

  // Generate mailto link
  const handleEmailShare = useCallback(async () => {
    try {
      const summary = formatTrackSummary();
      const subject = encodeURIComponent(`Track: ${track.name}`);
      const body = encodeURIComponent(summary);
      window.open(`mailto:?subject=${subject}&body=${body}`, '_blank');
    } catch (error) {
      console.error('Failed to create email:', error);
      showStatus('Failed to create email', false);
    }
  }, [track.name, formatTrackSummary, showStatus]);

  return (
    <>
      <div className="modal-backdrop" onClick={onClose} />
      <div className={`share-modal share-modal--${theme}`}>
        <div className="share-modal__header">
          <h3 className="share-modal__title">Share Track</h3>
          <span className="share-modal__route-name">{track.name}</span>
          <button className="share-modal__close" onClick={onClose}>
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>

        {/* Status message */}
        {status !== 'idle' && (
          <div className={`share-modal__status share-modal__status--${status}`}>
            {status === 'loading' && (
              <svg className="share-modal__spinner" width="16" height="16" viewBox="0 0 24 24">
                <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="3" fill="none" strokeDasharray="31.4" strokeDashoffset="10" />
              </svg>
            )}
            {status === 'success' && (
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <polyline points="20 6 9 17 4 12" />
              </svg>
            )}
            {status === 'error' && (
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="12" cy="12" r="10" />
                <line x1="15" y1="9" x2="9" y2="15" />
                <line x1="9" y1="9" x2="15" y2="15" />
              </svg>
            )}
            <span>{statusMessage}</span>
          </div>
        )}

        <div className="share-modal__content">
          {/* Track Info Section */}
          <div className="share-modal__section">
            <h4 className="share-modal__section-title">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
              </svg>
              Track Info
            </h4>
            <div className="share-modal__track-stats">
              <div className="share-modal__stat">
                <span className="share-modal__stat-label">Distance</span>
                <span className="share-modal__stat-value">{(track.total_distance_nm || 0).toFixed(2)} nm</span>
              </div>
              <div className="share-modal__stat">
                <span className="share-modal__stat-label">Points</span>
                <span className="share-modal__stat-value">{track.point_count}</span>
              </div>
              {track.started_at && track.ended_at && (
                <div className="share-modal__stat">
                  <span className="share-modal__stat-label">Duration</span>
                  <span className="share-modal__stat-value">
                    {(() => {
                      const start = new Date(track.started_at!);
                      const end = new Date(track.ended_at!);
                      const durationMs = end.getTime() - start.getTime();
                      const hours = Math.floor(durationMs / (1000 * 60 * 60));
                      const minutes = Math.floor((durationMs % (1000 * 60 * 60)) / (1000 * 60));
                      return hours > 0 ? `${hours}h ${minutes}m` : `${minutes}m`;
                    })()}
                  </span>
                </div>
              )}
            </div>
          </div>

          {/* Text Sharing Section */}
          <div className="share-modal__section">
            <h4 className="share-modal__section-title">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                <polyline points="14 2 14 8 20 8" />
                <line x1="16" y1="13" x2="8" y2="13" />
                <line x1="16" y1="17" x2="8" y2="17" />
              </svg>
              Text Summary
            </h4>
            <div className="share-modal__buttons">
              <button className="share-modal__btn" onClick={handleCopySummary}>
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                  <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                </svg>
                <span>Copy Summary</span>
                <small>Track details as text</small>
              </button>
            </div>
          </div>

          {/* GPX Section */}
          <div className="share-modal__section">
            <h4 className="share-modal__section-title">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                <polyline points="14 2 14 8 20 8" />
                <path d="M12 18v-6" />
                <path d="M9 15l3 3 3-3" />
              </svg>
              GPX File
            </h4>
            <div className="share-modal__buttons">
              <button className="share-modal__btn" onClick={handleCopyGpx}>
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                  <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                </svg>
                <span>Copy GPX to Clipboard</span>
                <small>Paste into messages or files</small>
              </button>
              <button className="share-modal__btn" onClick={handleDownloadGpx}>
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                  <polyline points="7 10 12 15 17 10" />
                  <line x1="12" y1="15" x2="12" y2="3" />
                </svg>
                <span>Save GPX File</span>
                <small>Download to your device</small>
              </button>
            </div>
          </div>

          {/* Quick Share Section */}
          <div className="share-modal__section">
            <h4 className="share-modal__section-title">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="18" cy="5" r="3" />
                <circle cx="6" cy="12" r="3" />
                <circle cx="18" cy="19" r="3" />
                <line x1="8.59" y1="13.51" x2="15.42" y2="17.49" />
                <line x1="15.41" y1="6.51" x2="8.59" y2="10.49" />
              </svg>
              Quick Share
            </h4>
            <div className="share-modal__buttons share-modal__buttons--row">
              <button className="share-modal__btn share-modal__btn--icon" onClick={handleEmailShare} title="Share via Email">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" />
                  <polyline points="22,6 12,13 2,6" />
                </svg>
              </button>
              <button className="share-modal__btn share-modal__btn--icon" onClick={handleSystemShare} title="System Share">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <circle cx="18" cy="5" r="3" />
                  <circle cx="6" cy="12" r="3" />
                  <circle cx="18" cy="19" r="3" />
                  <line x1="8.59" y1="13.51" x2="15.42" y2="17.49" />
                  <line x1="15.41" y1="6.51" x2="8.59" y2="10.49" />
                </svg>
              </button>
            </div>
          </div>
        </div>

        <div className="share-modal__footer">
          <span className="share-modal__hint">
            Tip: GPX files work with most navigation apps and chart plotters
          </span>
        </div>
      </div>
    </>
  );
}
